name: Prueba tokens

on:
  push:

jobs:
  comprobar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comprobar DEV_TOKEN
        shell: powershell
        run: |
          if ("${{ secrets.DEV_TOKEN }}" -ne "$env:LOCAL_DEV_TOKEN") {
            Write-Error "DEV_TOKEN no coincide"
            exit 1
          }
          Write-Host "DEV_TOKEN coincide correctamente"
# Segunda prueba
# Prueba correcta final
# Prueba fallida final
